// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2_sjIb05juKnHiPBPnsuaMHf9beOpzag',
    appId: '1:428520790344:web:513e289f05f65938a6bb7d',
    messagingSenderId: '428520790344',
    projectId: 'groove-nomad-dff97',
    authDomain: 'groove-nomad-dff97.firebaseapp.com',
    storageBucket: 'groove-nomad-dff97.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkbL3aoJuZTgk3YhtFPPBt8z5u1ODQPnw',
    appId: '1:428520790344:android:de3134f06dacd539a6bb7d',
    messagingSenderId: '428520790344',
    projectId: 'groove-nomad-dff97',
    storageBucket: 'groove-nomad-dff97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4l4PGL1Ni5Yp_uNSrAul-lMcfQM_bYZo',
    appId: '1:428520790344:ios:0668f75de48ab3cca6bb7d',
    messagingSenderId: '428520790344',
    projectId: 'groove-nomad-dff97',
    storageBucket: 'groove-nomad-dff97.firebasestorage.app',
    iosBundleId: 'com.example.grooveNomad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4l4PGL1Ni5Yp_uNSrAul-lMcfQM_bYZo',
    appId: '1:428520790344:ios:0668f75de48ab3cca6bb7d',
    messagingSenderId: '428520790344',
    projectId: 'groove-nomad-dff97',
    storageBucket: 'groove-nomad-dff97.firebasestorage.app',
    iosBundleId: 'com.example.grooveNomad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2_sjIb05juKnHiPBPnsuaMHf9beOpzag',
    appId: '1:428520790344:web:5fd3ab89449727c3a6bb7d',
    messagingSenderId: '428520790344',
    projectId: 'groove-nomad-dff97',
    authDomain: 'groove-nomad-dff97.firebaseapp.com',
    storageBucket: 'groove-nomad-dff97.firebasestorage.app',
  );
}
